<div id="single" class="content">
	<h1><a href='/single/<?php echo $article["id"]; ?>'><?php echo $article['title'];  ?></a></h1>
    <div class="meta">
    	<span>
    		<i class="icon-book"></i>
			<?php foreach($article['category'] as $c){ ?>
			<a href="/<?php echo $c['alias']; ?>"><?php echo $c['name']; ?></a>
			<?php } ?>
    	</span>
    	<span>
    		<i class="icon-tags"></i>
			<?php foreach($article['tag'] as $t){ ?>
			<a href="/tag/<?php echo $t['alias']; ?>"><?php echo $t['name']; ?></a>&nbsp;
			<?php } ?>
    	</span>
		<span>浏览：<?php echo $article['views']; ?> </span>
    	<span class="meta-date">日期：<?php echo @date('Y-m-d',strtotime($article['date'])); ?></span>
    </div>
	<div class="article">
		<?php 
			echo html_entity_decode($article['content']);
		 ?>
	</div>
	<div class="copyright">
		<p>技术交流Q号：80816909</p>
		<p>
			如非特殊说明，文章均为<a href="http://www.likuli.com">李苦李</a>原创。转载请注明原文地址：
			<a href="/single/<?php echo $article["id"]; ?>">www.likuli.com/single/<?php echo $article["id"]; ?></a>
		</p>	
	</div>
	<div class="pre_and_next">
		<ul>
		<?php if($pre){ ?>
		<li>
			<i class="icon-double-angle-left"></i> 上一篇：
			<a href="/single/<?php echo $pre['id']; ?>"><?php echo $pre['title']; ?></a>
		</li>
		<?php } ?>
		<?php if($next){ ?>
		<li class="fr">
			<i class="icon-double-angle-right"></i> 下一篇：
			<a href="/single/<?php echo $next['id']; ?>"><?php echo $next['title']; ?></a>
		</li>
		<?php } ?>
		</ul>
	</div>

	<!--高速版，加载速度快，使用前需测试页面的兼容性-->
	<div id="SOHUCS"></div>
	<script>  
		//(function(){    
			//var appid = 'cyrBWQILD', conf = 'prod_667db057be81c120b5bbf94263ba860e';    
			//var doc = document,    
			//s = doc.createElement('script'),    
			//h = doc.getElementsByTagName('head')[0] || doc.head || doc.documentElement;    
			//s.type = 'text/javascript';    
			//s.charset = 'utf-8';    
			//s.src =  'http://assets.changyan.sohu.com/upload/changyan.js?conf='+ conf +'&appid=' + appid;    
			//h.insertBefore(s,h.firstChild);    
			//window.SCS_NO_IFRAME = true;  
		//})()
	</script>                

</div><!-- End .main -->
