<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta name="baidu-tc-verification" content="1f83110ac5f275e39f7915cade5cdff8" />
	<meta name="baidu-site-verification" content="vreX1UZny7" />
	<meta property="qc:admins" content="044146767764135416375" />
	<title>
	<?php if($homepage){ 
		echo "李苦李 - 互联网技术博客";
	}else{ 
		echo "${title} - 李苦李";		
	} 
	?>
	</title>
	<link rel="stylesheet" href="/public/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" href="/public/bootstrap/css/font-awesome.min.css" />
	<link rel="stylesheet" href="/public/css/likuli.css" />
	<link rel="stylesheet" href="/public/syntaxhighlighter/styles/shCoreDefault.css" />
	<script type="text/javascript" src="/public/syntaxhighlighter/scripts/shCore.js"></script>
	<script type="text/javascript">SyntaxHighlighter.all();</script>
	<script>
		var _hmt = _hmt || [];
		(function() {
			  var hm = document.createElement("script");
			    hm.src = "//hm.baidu.com/hm.js?0119a5dc5c57f8868b52f71b2a2ea05f";
			    var s = document.getElementsByTagName("script")[0]; 
				  s.parentNode.insertBefore(hm, s);
		})();
	</script>

</head>
<body>
<div id="wrapper">
	<header id="header">
		<div class="holder">
			<div id="logo">
				<?php if($homepage){ ?>
				<h1><a href="/">李苦李</a></h1>
				<?php }else{ ?>
				<h2><a href="/">李苦李</a></h2>
				<?php } ?>
			</div>
			<!--
			<nav id="nav">
				<ul>
					<li><a href="/">首页</a></li>
					<li><a href="/">专题</a></li>
					<li><a href="/">关于</a></li>
					<li><a href="/">网站地图</a></li>
				</ul>
			</nav>
			-->
		</div>
	</header>
	<main id="main" role="main">

